version: "3"

services:

  node1:
    container_name: rabbitmq_node1
    hostname: node1
    image: rabbitmq:3.8.6-management
    ports:
      - 5672:5672
      - 15672:15672
    volumes: 
      - ./config/rabbitmq_node_1:/config/
    env_file: rabbitmq.env

  node2:
    container_name: rabbitmq_node2
    hostname: node2
    links:
      - node1
    image: rabbitmq:3.8.6-management
    ports:
      - 6672:5672
      - 16672:15672
    volumes: 
      - ./config/rabbitmq_node_2:/config/
    env_file: rabbitmq.env

  node3:
    container_name: rabbitmq_node3
    hostname: node3
    links:
      - node1
    image: rabbitmq:3.8.6-management
    ports:
      - 7672:5672
      - 17672:15672
    volumes: 
      - ./config/rabbitmq_node_3:/config/
    env_file: rabbitmq.env
